<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPSIEQ33\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPSIEQ33/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPSIEQ33.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPSIEQ33\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPSIEQ33\App_KernelProdContainer([
    'container.build_hash' => 'PSIEQ33',
    'container.build_id' => '51785d8f',
    'container.build_time' => 1723109740,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPSIEQ33');
