<?php

namespace ContainerU4KuqMa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5rpm7dmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5rpm7dm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5rpm7dm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'availabilityRepository' => ['privates', 'App\\Repository\\AvailabilityRepository', 'getAvailabilityRepositoryService', true],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'availabilityRepository' => 'App\\Repository\\AvailabilityRepository',
            'hasher' => '?',
            'paginator' => '?',
        ]);
    }
}
