<?php

namespace ContainerPSIEQ33;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvailabilityRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AvailabilityRepository' shared autowired service.
     *
     * @return \App\Repository\AvailabilityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AvailabilityRepository'] = new \App\Repository\AvailabilityRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
