<?php

namespace ContainerPSIEQ33;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicleTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\VehicleType' shared autowired service.
     *
     * @return \App\Form\VehicleType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\VehicleType'] = new \App\Form\VehicleType();
    }
}
