<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU4KuqMa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU4KuqMa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU4KuqMa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU4KuqMa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU4KuqMa\App_KernelDevDebugContainer([
    'container.build_hash' => 'U4KuqMa',
    'container.build_id' => '0de73112',
    'container.build_time' => 1723059062,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU4KuqMa');
